jenkins:
    image: autopilotpattern/jenkins
    restart: always
    mem_limit: 8g
    ports:
      - 80
      - 22
    labels:
      - triton.cns.services=jenkins
    env_file: _env

# Start with a single host which will bootstrap the cluster.
# In production we'll want to use an HA cluster.
consul:
    image: progrium/consul:latest
    restart: always
    mem_limit: 128m
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
       - 127.0.0.1
    labels:
      - triton.cns.services=consul
    command: -server -bootstrap -ui-dir /ui
