jenkins:
    image: autopilotpattern/jenkins
    restart: always
    mem_limit: 8g
    ports:
      - 8000
      - 22
    labels:
      - triton.cns.services=jenkins
    env_file: _env

# reverse proxy for protecting Jenkins w/ TLS
nginx:
    image: autopilotpattern/jenkins-nginx
    restart: always
    mem_limit: 256m
    environment:
      - BACKEND=jenkins
      - CONSUL_AGENT=1
      - ACME_ENV=
      - ACME_DOMAIN=
    env_file: _env
    labels:
      - triton.cns.services=jenkins-nginx
    ports:
      - 80
      - 443
      - 9090

# Start with a single host which will bootstrap the cluster.
# In production we'll want to use an HA cluster.
consul:
    image: progrium/consul:latest
    restart: always
    mem_limit: 128m
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
       - 127.0.0.1
    labels:
      - triton.cns.services=jenkins-consul
    command: -server -bootstrap -ui-dir /ui
