# Start with a single host which will bootstrap the cluster. Once the
# cluster is bootstrapped we can set BOOTSTRAP_HOST and scale up
# more Consul instances.
# By using automatic bootstrapping via `-bootstrap-expect` and adding
# the environment variable, we can avoid having to use links. The
# environment variable is used once at bootstrap and then forever
# discarded by that node.
consul:
    image: misterbisson/triton-consul:latest
    restart: always
    mem_limit: 128m
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
       - 127.0.0.1
    environment:
       - BOOTSTRAP_HOST
    command: >
      /opt/containerbuddy/containerbuddy
      -config file:///etc/containerbuddy.json
      /bin/consul agent -server
                  -config-dir=/config
                  -ui-dir /ui
                  -bootstrap-expect 3

jenkins:
    image: dekobon/triton-jenkins
    links:
      - consul
    mem_limit: 8g
    ports:
      - 80
      - 22
    restart: always
    labels:
        - triton.cns.services=jenkins
#    command: >
#      /opt/containerbuddy/containerbuddy
#      -config file:///opt/containerbuddy/app.json
#      /usr/local/bin/triton-jenkins.sh
